language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install .
script:
  - coverage run --source=depfinder -m unittest discover -s tests
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
