language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -U pip
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install .
script:
  - py.test --cov-report=xml --cov=depfinder
after_success:
  - bash <(curl -s https://codecov.io/bash)
